name: CI - Run Tests

on:
  push:
    branches:
      - "**" # Trigger on push to any branch
  pull_request:
    branches:
      - "**" # Trigger on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test
